---
- name: Install packages
  shell: rpm-ostree install etcd flannel kubernetes-node
  register: command_result
  ignore_errors: true

- name: restart hosts
  shell: sleep 3 && shutdown -r now
  async: 1
  poll: 0
  when: "'systemctl reboot' in command_result.stdout"

- name: wait for hosts to come back up
  local_action: wait_for host={{ inventory_hostname }} port=22 state=started delay=15 timeout=120
  sudo: false

- name: Place master component service files
  template: src={{ item }} dest=/etc/systemd/system/
  with_items:
    - kube-apiserver.service
    - kube-scheduler.service
    - kube-controller-manager.service
  when: inventory_hostname in groups['masters']

- name: daemon-reload
  raw: systemctl daemon-reload
  when: inventory_hostname in groups['masters']
